export type SpecialLocation = [
  fullName: string,
  slug: string,
  lat: number,
  lng: number,
  areaId?: string
];
export const LARGE_CITIES: SpecialLocation[] = [
  ["Tokyo, Japan", "Tokyo", 35.68972, 139.69222],
  ["Delhi, India", "Delhi", 28.61, 77.23],
  ["Shanghai, China", "Shanghai", 31.22861, 121.47472, "shanghai-suzhou"],
  ["São Paulo, Brazil", "São Paulo", -23.55, -46.633],
  ["Mexico City, Mexico", "Mexico City", 19.433, -99.133],
  ["Cairo, Egypt", "Cairo", 30.04444, 31.23583],
  ["Mumbai, India", "Mumbai", 19.07611, 72.8775],
  ["Beijing, China", "Beijing", 39.90667, 116.3975],
  ["Dhaka, Bangladesh", "Dhaka", 23.76444, 90.38889],
  ["Osaka, Japan", "Osaka", 34.69389, 135.50222],
  ["New York City, USA", "NYC", 40.71278, -74.00611],
  ["Tehran, Iran", "Tehran", 35.68889, 51.38972],
  ["Karachi, Pakistan", "Karachi", 24.86, 67.01],
  ["Kolkata, India", "Kolkata", 22.5726, 88.3639],
  ["Buenos Aires, Argentina", "Buenos Aires", -34.60372, -58.38159],
  ["Chongqing, China", "Chongqing", 29.563, 106.551],
  ["Istanbul, Turkey", "Istanbul", 41.0082, 28.9784],
  ["Manila, Philippines", "Manila", 14.5995, 120.9842],
  ["Lagos, Nigeria", "Lagos", 6.5244, 3.3792],
  ["Rio de Janeiro, Brazil", "Rio", -22.90685, -43.1729],
  ["Tianjin, China", "Tianjin", 39.3433, 117.3616],
  ["Kinshasa, DR Congo", "Kinshasa", -4.44193, 15.2663],
  ["Guangzhou, China", "Guangzhou", 23.12911, 113.26439, "pearl-river-delta"],
  [
    "Los Angeles, California, USA",
    "LA",
    34.05223,
    -118.24368,
    "los-angeles-area",
  ],
  ["Shenzhen, China", "Shenzhen", 22.5431, 114.05786, "pearl-river-delta"],
  ["Lahore, Pakistan", "Lahore", 31.52037, 74.35875],
  ["Bengaluru, India", "Bangalore", 12.9716, 77.5946],
  ["Bogotá, Colombia", "Bogotá", 4.711, -74.0721],
  ["Jakarta, Indonesia", "Jakarta", -6.20876, 106.8456],
  ["Chennai, India", "Chennai", 13.08268, 80.27072],
  ["Lima, Peru", "Lima", -12.04637, -77.04279],
  ["Bangkok, Thailand", "Bangkok", 13.75633, 100.50177],
  ["Seoul, South Korea", "Seoul", 37.56654, 126.978],
  ["Nagoya, Japan", "Nagoya", 35.18145, 136.9064],
  ["Hyderabad, India", "Hyderabad", 17.38504, 78.48667],
  ["Chicago, Illinois, USA", "Chicago", 41.87811, -87.6298],
  ["Chengdu, China", "Chengdu", 30.57281, 104.0668],
  ["Nanjing, China", "Nanjing", 32.06025, 118.79687],
  ["Wuhan, China", "Wuhan", 30.59285, 114.30554],
  ["Ho Chi Minh City, Vietnam", "Ho Chi Minh", 10.8231, 106.6297],
  ["Luanda, Angola", "Luanda", -8.83833, 13.23444],
  ["Ahmedabad, India", "Ahmedabad", 23.0225, 72.57136],
  ["Kuala Lumpur, Malaysia", "KL", 3.139, 101.68685],
  ["Xi'an, China", "Xi'an", 34.34157, 108.93977],
  ["Hong Kong, China", "Hong Kong", 22.3193, 114.16936, "pearl-river-delta"],
  ["Dongguan, China", "Dongguan", 23.02067, 113.75179, "pearl-river-delta"],
  ["Hangzhou, China", "Hangzhou", 30.27408, 120.15507],
  ["Foshan, China", "Foshan", 23.02148, 113.12144, "pearl-river-delta"],
  ["Shenyang, China", "Shenyang", 41.80563, 123.43147],
  ["Riyadh, Saudi Arabia", "Riyadh", 24.71355, 46.6753],
  ["Baghdad, Iraq", "Baghdad", 33.31524, 44.36606],
  ["Santiago, Chile", "Santiago", -33.44889, -70.66927],
  ["Surat, India", "Surat", 21.17024, 72.83106],
  ["Suzhou, China", "Suzhou", 31.29834, 120.58319, "shanghai-suzhou"],
  ["Pune, India", "Pune", 18.52043, 73.85674],
  ["Harbin, China", "Harbin", 45.80377, 126.53497],
  ["Houston, Texas, USA", "Houston", 29.76043, -95.3698],
  ["Dallas, Texas, USA", "Dallas", 32.77666, -96.79699],
  ["Toronto, Ontario, Canada", "Toronto", 43.65323, -79.38318],
  ["Dar es Salaam, Tanzania", "Dar", -6.79235, 39.20833],
  ["Miami, Florida, USA", "Miami", 25.76168, -80.19179],
  ["Belo Horizonte, Brazil", "Belo Horizonte", -19.91668, -43.93449],
  ["Singapore, Singapore", "Singapore", 1.35208, 103.81984],
  ["Philadelphia, Pennsylvania, USA", "Philly", 39.95258, -75.16522],
  ["Atlanta, USA", "Atlanta", 33.749, -84.38798],
  ["Fukuoka, Japan", "Fukuoka", 33.59035, 130.40172],
  ["Khartoum, Sudan", "Khartoum", 15.50065, 32.5599],
  ["Johannesburg, South Africa", "Joburg", -26.2041, 28.04731],
  ["Qingdao, China", "Qingdao", 36.06711, 120.38261],
  ["Dalian, China", "Dalian", 38.91369, 121.61476],
  ["Washington, Washington DC, USA", "Washington DC", 38.90719, -77.03687],
  ["Yangon, Myanmar", "Yangon", 16.84086, 96.17352],
  ["Alexandria, Egypt", "Alexandria", 31.20009, 29.91874],
  ["Jinan, China", "Jinan", 36.65122, 117.12009],
  ["Guadalajara, Mexico", "Guadalajara", 20.6597, -103.3496],
  ["Monterrey, Mexico", "Monterrey", 25.68661, -100.31611],
  ["Sydney, Australia", "Sydney", -33.86882, 151.2093],
  ["Urumqi, China", "Urumqi", 43.82559, 87.61685],
  ["Changsha, China", "Changsha", 28.22821, 112.93881],
  ["Cape Town, South Africa", "Cape Town", -33.92487, 18.42406],
  ["Jeddah, Saudi Arabia", "Jeddah", 21.48581, 39.1925],
  ["Brasília, Brazil", "Brasília", -15.82669, -47.92182],
  ["Kunming, China", "Kunming", 25.03889, 102.71827],
  ["Changchun, China", "Changchun", 43.81602, 125.32357],
  ["Kabul, Afghanistan", "Kabul", 34.55535, 69.20748],
  ["Yaoundé, Cameroon", "Yaoundé", 3.848, 11.5021],
  ["Hefei, China", "Hefei", 31.82059, 117.22724],
  ["Ningbo, China", "Ningbo", 29.86834, 121.544],
  ["Shantou, China", "Shantou", 23.35409, 116.68197],
  ["Kano, Nigeria", "Kano", 12.00218, 8.59196],
  ["Tel Aviv, Israel", "Tel Aviv", 32.0853, 34.78177],
  ["New Taipei, Taiwan", "New Taipei", 25.01698, 121.46279],
  ["Shijiazhuang, China", "Shijiazhuang", 38.04276, 114.5143],
  ["Jaipur, India", "Jaipur", 26.91243, 75.78727],

  /* Canada large cities */

  ["Toronto, Canada", "Toronto", 43.706, -79.399, "greater-toronto"],
  [
    "Mississauga, Canada",
    "Mississauga",
    43.59531,
    -79.64058,
    "greater-toronto",
  ], // source  [oai_citation:0‡Coordinates Finder](https://www.coordinatesfinder.com/coordinates/351631-hamilton-on-canada?utm_source=chatgpt.com)
  ["Brampton, Canada", "Brampton", 43.68341, -79.76633, "greater-toronto"], // source  [oai_citation:1‡Geodatos](https://www.geodatos.net/en/coordinates/canada/brampton?utm_source=chatgpt.com)
  ["Montreal, Canada", "Montreal", 45.509, -73.588, "montreal"],
  ["Quebec City, Canada", "Quebec City", 46.81388, -71.20798, "quebec-city"], // source  [oai_citation:2‡Coordinates Marker](https://www.coordinatesmarker.com/coordinates/1893407-quebec-city-qc?utm_source=chatgpt.com) [oai_citation:3‡us.maptons.com](https://us.maptons.com/422?utm_source=chatgpt.com)
  ["Calgary, Canada", "Calgary", 51.05, -114.085, "calgary"],
  ["Edmonton, Canada", "Edmonton", 53.55, -113.469, "edmonton"],
  ["Ottawa, Canada", "Ottawa", 45.411, -75.698, "ottawa"],
  ["Winnipeg, Canada", "Winnipeg", 49.89556, -97.13861, "winnipeg"], // source  [oai_citation:4‡Wikipedia](https://en.wikipedia.org/wiki/Winnipeg?utm_source=chatgpt.com)
  ["Vancouver, Canada", "Vancouver", 49.26083, -123.11389, "vancouver"], // source  [oai_citation:5‡Wikipedia](https://en.wikipedia.org/wiki/Vancouver?utm_source=chatgpt.com)
  ["Hamilton, Canada", "Hamilton", 43.24278, -79.98944, "hamilton"], // source  [oai_citation:6‡Wikipedia](https://en.wikipedia.org/wiki/Hamilton%2C_Ontario?utm_source=chatgpt.com)
  ["Surrey, Canada", "Surrey", 49.19, -122.84889, "surrey"], // source  [oai_citation:7‡Wikipedia](https://en.wikipedia.org/wiki/Surrey%2C_British_Columbia?utm_source=chatgpt.com)

  /* Europe large cities */
  ["Moscow, Russia", "Moscow", 55.75, 37.61, "moscow"],
  ["Paris, France", "Paris", 48.85, 2.35, "paris"],
  ["London, UK", "London", 51.5, -0.12, "london"],
  ["Madrid, Spain", "Madrid", 40.42, -3.7, "madrid"],
  ["Barcelona, Spain", "Barcelona", 41.38, 2.17, "barcelona"],
  [
    "Saint Petersburg, Russia",
    "Saint Petersburg",
    59.93428,
    30.3351,
    "saint-petersburg",
  ],
  ["Rome, Italy", "Rome", 41.9, 12.5, "rome"],
  ["Berlin, Germany", "Berlin", 52.52, 13.41, "berlin"],
  ["Athens, Greece", "Athens", 37.98, 23.72, "athens"],
  ["Milan, Italy", "Milan", 45.47, 9.19, "milan"],
  ["Kyiv, Ukraine", "Kyiv", 50.45, 30.52, "kyiv"],
  ["Lisbon, Portugal", "Lisbon", 38.72, -9.13, "lisbon"],
  ["Budapest, Hungary", "Budapest", 47.5, 19.04, "budapest"],
  ["Brussels, Belgium", "Brussels", 50.85, 4.35, "brussels"],
  ["Hamburg, Germany", "Hamburg", 53.55, 10, "hamburg"],
  ["Warsaw, Poland", "Warsaw", 52.23, 21.01, "warsaw"],
  ["Vienna, Austria", "Vienna", 48.21, 16.37, "vienna"],
  ["Frankfurt, Germany", "Frankfurt", 50.11, 8.68, "frankfurt"],
  ["Munich, Germany", "Munich", 48.14, 11.58, "munich"],
  ["Bucharest, Romania", "Bucharest", 44.43, 26.11, "bucharest"],

  /* California Largest Cities */
  [
    "San Diego, California, USA",
    "San Diego",
    32.7157,
    -117.1611,
    "san-diego-area",
  ],
  [
    "San Jose, California, USA",
    "San Jose",
    37.3382,
    -121.8863,
    "san-jose-area",
  ],
  [
    "San Francisco, California, USA",
    "San Francisco",
    37.7749,
    -122.4194,
    "sf-bay-area",
  ],
  [
    "Fresno, California, USA",
    "Fresno",
    36.7378,
    -119.7871,
    "fresno-california",
  ],
  [
    "Sacramento, California, USA",
    "Sacramento",
    38.5816,
    -121.4944,
    "sacramento-california",
  ],
  [
    "Long Beach, California, USA",
    "Long Beach",
    33.7701,
    -118.1937,
    "los-angeles-area",
  ],
  ["Oakland, California, USA", "Oakland", 37.8044, -122.2711, "sf-bay-area"],
  [
    "Bakersfield, California, USA",
    "Bakersfield",
    35.3733,
    -119.0187,
    "bakersfield-california",
  ],
  [
    "Anaheim, California, USA",
    "Anaheim",
    33.8366,
    -117.9143,
    "los-angeles-area",
  ],
  [
    "Stockton, California, USA",
    "Stockton",
    37.9577,
    -121.2908,
    "stockton-california",
  ],
  [
    "Riverside, California, USA",
    "Riverside",
    33.9806,
    -117.3755,
    "los-angeles-area",
  ],
  ["Irvine, California, USA", "Irvine", 33.6846, -117.8265, "los-angeles-area"],
  [
    "Santa Ana, California, USA",
    "Santa Ana",
    33.7455,
    -117.8677,
    "los-angeles-area",
  ],
  [
    "Chula Vista, California, USA",
    "Chula Vista",
    32.6401,
    -117.0842,
    "san-diego-area",
  ],
  ["Fremont, California, USA", "Fremont", 37.5483, -121.9886, "sf-bay-area"],
  [
    "San Bernardino, California, USA",
    "San Bernardino",
    34.1083,
    -117.2898,
    "los-angeles-area",
  ],
  [
    "Modesto, California, USA",
    "Modesto",
    37.6391,
    -120.9969,
    "modesto-california",
  ],
  [
    "Fontana, California, USA",
    "Fontana",
    34.0922,
    -117.435,
    "los-angeles-area",
  ],
  [
    "Moreno Valley, California, USA",
    "Moreno Valley",
    33.9425,
    -117.2297,
    "los-angeles-area",
  ],
] as const;

export const DARK_SITES: SpecialLocation[] = [
  /* Dark Sky Parks and Reserves and National Parks */
  [
    "Yellowstone National Park, Wyoming/Montana/Idaho, USA",
    "Yellowstone",
    44.6,
    -110.5,
    "yellowstone",
  ],
  [
    "Yosemite National Park, California, USA",
    "Yosemite",
    37.8651,
    -119.5383,
    "yosemite",
  ],
  [
    "Sequoia National Park, California, USA",
    "Sequoia",
    36.4864,
    -118.5658,
    "sequoia",
  ],
  [
    "Kings Canyon National Park, California, USA",
    "Kings Canyon",
    36.8879,
    -118.5551,
    "kingscanyon",
  ],
  [
    "Pinnacles National Park, California, USA",
    "Pinnacles",
    36.4915,
    -121.1972,
    "pinnacles",
  ],
  [
    "Redwood National and State Parks, California, USA",
    "Redwood",
    41.2132,
    -124.0046,
    "redwood",
  ],
  [
    "Channel Islands National Park, California, USA",
    "Channel Islands",
    34.0069,
    -119.7785,
    "channelislands",
  ],
  [
    "Glacier National Park, Montana, USA",
    "Glacier",
    48.7596,
    -113.787,
    "glacier",
  ],
  [
    "Grand Teton National Park, Wyoming, USA",
    "Grand Teton",
    43.7908,
    -110.6849,
    "grandteton",
  ],
  [
    "Rocky Mountain National Park, Colorado, USA",
    "Rocky Mountain",
    40.3428,
    -105.6836,
    "rockymountain",
  ],
  [
    "White Sands National Park, New Mexico, USA",
    "White Sands",
    32.7797,
    -106.1717,
    "whitesands",
  ],
  [
    "Mojave National Preserve, California, USA",
    "Mojave",
    35.1417,
    -115.5104,
    "mojave",
  ],
  [
    "Great Smoky Mountains National Park, Tennessee/North Carolina, USA",
    "Great Smoky Mountains",
    35.6118,
    -83.4895,
    "greatsmokymountains",
  ],
  [
    "Everglades National Park, Florida, USA",
    "Everglades",
    25.2866,
    -80.8987,
    "everglades",
  ],
  [
    "Badlands National Park, South Dakota, USA",
    "Badlands",
    43.8554,
    -102.3397,
    "badlands",
  ],
  ["Acadia National Park, Maine, USA", "Acadia", 44.3386, -68.2733, "acadia"],
  [
    "Haleakalā National Park, Hawaii, USA",
    "Haleakalā",
    20.7097,
    -156.2532,
    "haleakala",
  ],
  ["Denali National Park, Alaska, USA", "Denali", 63.1148, -151.1926, "denali"],
  [
    "Statue of Liberty NM, New York, USA",
    "Statue of Liberty",
    40.6892,
    -74.0445,
    "statueofliberty",
  ],
  [
    "Natural Bridges National Monument, Utah, USA",
    "Natural Bridges",
    37.6,
    -110.01,
    "naturalbridges",
  ],
  [
    "Death Valley National Park, California/Nevada, USA",
    "Death Valley",
    36.5323,
    -117.0794,
    "deathvalley",
  ],
  [
    "Joshua Tree National Park, California, USA",
    "Joshua Tree",
    33.87,
    -115.9,
    "joshuatree",
  ],
  ["Arches National Park, Utah, USA", "Arches", 38.68, -109.57, "arches"],
  [
    "Canyonlands National Park, Utah, USA",
    "Canyonlands",
    38.33,
    -109.88,
    "canyonlands",
  ],
  [
    "Capitol Reef National Park, Utah, USA",
    "Capitol Reef",
    38.36,
    -111.26,
    "capitolreef",
  ],
  [
    "Bryce Canyon National Park, Utah, USA",
    "Bryce Canyon",
    37.63,
    -112.17,
    "brycecanyon",
  ],
  [
    "Grand Canyon National Park, Arizona, USA",
    "Grand Canyon",
    36.06,
    -112.12,
    "grandcanyon",
  ],
  [
    "Great Sand Dunes National Park, Colorado, USA",
    "Great Sand Dunes",
    37.73,
    -105.51,
    "greatsanddunes",
  ],
  ["Big Bend National Park, Texas, USA", "Big Bend", 29.22, -103.24, "bigbend"],
  [
    "Black Canyon of the Gunnison NP, Colorado, USA",
    "Black Canyon",
    38.58,
    -107.74,
    "blackcanyon",
  ],
  [
    "Big Cypress National Preserve, Florida, USA",
    "Big Cypress",
    25.86,
    -81.03,
    "bigcypress",
  ],
  ["Glacier National Park, Montana, USA", "Glacier", 48.7, -113.72, "glacier"],
  [
    "Petrified Forest National Park, Arizona, USA",
    "Petrified Forest",
    35.98,
    -109.77,
    "petrifiedforest",
  ],
  [
    "Craters of the Moon NM, Idaho, USA",
    "Craters of the Moon",
    43.43,
    -113.48,
    "cratersofthemoon",
  ],
  [
    "Chaco Culture National Historical Park, New Mexico, USA",
    "Chaco Culture",
    36.06,
    -107.97,
    "chacoculture",
  ],
  [
    "Cedar Breaks National Monument, Utah, USA",
    "Cedar Breaks",
    37.64,
    -112.85,
    "cedarbreaks",
  ],
  [
    "Capulin Volcano National Monument, New Mexico, USA",
    "Capulin Volcano",
    36.78,
    -103.97,
    "capulinvolcano",
  ],
  [
    "Florissant Fossil Beds NM, Colorado, USA",
    "Florissant Fossil Beds",
    38.91,
    -105.17,
    "florissant",
  ],
  [
    "Fort Union National Monument, New Mexico, USA",
    "Fort Union",
    35.91,
    -105.15,
    "fortunion",
  ],
  [
    "Hovenweep National Monument, Utah/Colorado, USA",
    "Hovenweep",
    37.28,
    -109.12,
    "hovenweep",
  ],
  [
    "Salinas Pueblo Missions NM, New Mexico, USA",
    "Salinas Pueblo Missions",
    34.5,
    -106.75,
    "salinaspueblo",
  ],
  [
    "Valles Caldera National Preserve, New Mexico, USA",
    "Valles Caldera",
    35.82,
    -106.47,
    "vallescaldera",
  ],
  [
    "Anza‑Borrego Desert State Park, California, USA",
    "Anza‑Borrego",
    33.26,
    -116.4,
    "anzaborrego",
  ],
  [
    "Antelope Island State Park, Utah, USA",
    "Antelope Island",
    40.96,
    -112.21,
    "antelopeisland",
  ],
  [
    "Headlands International Dark Sky Park, Michigan, USA",
    "Headlands",
    45.78,
    -84.78,
    "headlands",
  ],
  [
    "Oracle State Park (Oracle ID Sky Park), Arizona, USA",
    "Oracle",
    32.61,
    -110.73,
    "oracle",
  ],
  [
    "Canyonlands International Dark Sky Park (overlap)",
    "Canyonlands (IDSP)",
    38.33,
    -109.88,
    "canyonlandsidsp",
  ],
  [
    "Copper Breaks State Park, Texas, USA",
    "Copper Breaks",
    34.11,
    -99.75,
    "copperbreaks",
  ],
  [
    "Clayton Lake State Park, New Mexico, USA",
    "Clayton Lake",
    36.58,
    -103.31,
    "claytonlake",
  ],
  [
    "Cherry Springs State Park, Pennsylvania, USA",
    "Cherry Springs",
    41.65,
    -77.82,
    "cherrysprings",
  ],
  [
    "Blue Ridge Observatory Star Park, North Carolina, USA",
    "Blue Ridge Observatory",
    35.93,
    -82.02,
    "blueridgeobservatory",
  ],
  [
    "Aotea/Great Barrier Island International Dark Sky Sanctuary, New Zealand",
    "Great Barrier Island",
    -36.17,
    175.38,
    "greatbarrierisland",
  ],
  [
    "Kerry International Dark Sky Reserve, Ireland",
    "Kerry",
    51.8969,
    -10.0894,
    "kerry",
  ],
  ["Mayo International Dark Sky Park, Ireland", "Mayo", 54.07, -9.69, "mayo"],
  [
    "Ramon Crater International Dark Sky Park, Israel",
    "Ramon Crater",
    30.58,
    34.82,
    "ramoncrater",
  ],
  [
    "Iriomote‑Ishigaki National Park International Dark Sky Park, Japan",
    "Iriomote‑Ishigaki",
    24.32,
    123.88,
    "iriomoteishigaki",
  ],
  [
    "NamibRand International Dark Sky Reserve, Namibia",
    "NamibRand",
    -25.12,
    15.99,
    "namibrand",
  ],
  [
    "Bükk National Park (Zselic), Hungary",
    "Bükk (Zselic)",
    48.05,
    20.53,
    "bukk",
  ],
  ["Hortobágy National Park, Hungary", "Hortobágy", 47.55, 21.12, "hortobagy"],
  [
    "Lauwersmeer National Park, Netherlands",
    "Lauwersmeer",
    53.35,
    6.19,
    "lauwersmeer",
  ],
  ["South Downs National Park, UK", "South Downs", 51.06, -0.69, "southdowns"],
  ["Snowdonia National Park, UK", "Snowdonia", 50.08, -4.08, "snowdonia"],
  [
    "Tomintoul and Glenlivet Dark Sky Park, UK",
    "Tomintoul & Glenlivet",
    57.24,
    -3.35,
    "tomintoulglenlivet",
  ],
  [
    "Galloway Forest Park, Scotland, UK",
    "Galloway Forest",
    55.03,
    -4.45,
    "gallowayforest",
  ],
  [
    "Great Basin National Park, NV, USA",
    "Great Basin",
    38.98,
    -114.3,
    "greatbasin",
  ],
  [
    "Flagstaff area NM & monuments, AZ, USA",
    "Flagstaff Monuments",
    35.2,
    -111.65,
    "flagstaffmonuments",
  ],
  [
    "Mammoth Cave National Park, Kentucky, USA",
    "Mammoth Cave",
    37.19,
    -86.13,
    "mammothcave",
  ],
  [
    "Buffalo National River, Arkansas, USA",
    "Buffalo River",
    35.91,
    -92.1,
    "buffaloriver",
  ],
  [
    "Cape Lookout National Seashore, North Carolina, USA",
    "Cape Lookout",
    34.61,
    -76.58,
    "capelookout",
  ],
  ["Curecanti NRA, Colorado, USA", "Curecanti", 38.52, -107.34, "curecanti"],
  [
    "Dinosaur National Monument, Colorado/Utah, USA",
    "Dinosaur NM",
    40.42,
    -108.99,
    "dinosaur",
  ],
  ["Mesa Verde NP, Colorado, USA", "Mesa Verde", 37.23, -108.46, "mesaverde"],
  [
    "Goosenecks State Park, Utah, USA",
    "Goosenecks",
    37.09,
    -110.76,
    "goosenecks",
  ],
  [
    "Pictured Rocks National Lakeshore, Michigan, USA",
    "Pictured Rocks",
    46.53,
    -86.65,
    "picturedrocks",
  ],
  [
    "Port Crescent State Park, Michigan, USA",
    "Port Crescent",
    44.13,
    -83.44,
    "portcrescent",
  ],
  ["Salar de Uyuni, Bolivia", "Salar de Uyuni", -20.13, -67.49],
  [
    "Tenerife (Teide area), Canary Islands, Spain",
    "Tenerife",
    28.27,
    -16.64,
    "tenerife",
  ],
  [
    "Mont‑Mégantic National Park, Québec, Canada",
    "Mont‑Mégantic",
    45.53,
    -71.32,
    "montmegantic",
  ],
  [
    "Aoraki Mackenzie International Dark Sky Reserve, NZ",
    "Aoraki Mackenzie",
    -44.0,
    170.3,
    "aorakimackenzie",
  ],
  ["Kaikōura Dark Sky Sanctuary, NZ", "Kaikōura", -42.4, 173.68, "kaikoura"],
  [
    "Pic du Midi, French Pyrenees, France",
    "Pic du Midi",
    42.94,
    0.14,
    "picdumidi",
  ],
  [
    "Millevaches Dark Sky Reserve, Limousin, France",
    "Millevaches",
    45.8,
    1.68,
    "millevaches",
  ],
  [
    "North York Moors National Park, England",
    "North York Moors",
    54.35,
    -0.87,
    "northyorkmoors",
  ],
  ["Rhön Dark Sky Reserve, Germany", "Rhön", 50.45, 10, "rhon"],
  ["Exmoor National Park, England", "Exmoor", 51.18, -3.68, "exmoor"],

  // === Auto-generated additional DARK_SITES from Go-Astronomy Bortle Class 2 list (first 60 entries) ===
  [
    "Worthington Glacier State Recreation Area, Alaska, USA",
    "Worthington Glacier",
    61.17029,
    -145.763445,
    "worthingtonglacier",
  ],
  [
    "Alamo Lake State Park, Arizona, USA",
    "Alamo Lake",
    34.232042,
    -113.603211,
    "alamolake",
  ],
  [
    "Flagstaff Area National Monument, Arizona, USA",
    "Flagstaff Area National Monument",
    35.234298,
    -111.676582,
    "flagstaffareanationalmonument",
  ],
  [
    "Kartchner Caverns State Park, Arizona, USA",
    "Kartchner Caverns",
    31.837604,
    -110.346519,
    "kartchnercaverns",
  ],
  [
    "Oracle State Park, Arizona, USA",
    "Oracle State Park",
    32.610283,
    -110.735434,
    "oraclestatepark",
  ],
  [
    "Petrified Forest National Park, Arizona, USA",
    "Petrified Forest",
    35.070021,
    -109.789377,
    "petrifiedforestnationalpark",
  ],
  [
    "Tonto Monument National Monument, Arizona, USA",
    "Tonto Monument",
    33.656852,
    -111.095021,
    "tontomonument",
  ],
  [
    "Tumacácori National Historical Park, Arizona, USA",
    "Tumacácori",
    31.568215,
    -111.050954,
    "tumacacorinationalhistoricalpark",
  ],
  [
    "Buffalo National River National Reserve, Arkansas, USA",
    "Buffalo National River",
    35.915947,
    -92.098089,
    "buffalonationalrivernationalreserve",
  ],
  [
    "Cossatot River State Park–Natural Area, Arkansas, USA",
    "Cossatot River",
    34.295821,
    -94.168077,
    "cossatotriverstateparknaturalarea",
  ],
  [
    "Queen Wilhelmina State Park, Arkansas, USA",
    "Queen Wilhelmina",
    34.685674,
    -94.369893,
    "queenwilhelminastatepark",
  ],
  [
    "Admiral William Standley State Recreation Area, California, USA",
    "Admiral William Standley",
    38.07512,
    -122.588877,
    "admiralwilliamstandleystate",
  ],
  [
    "Ahjumawi Lava Springs State Park, California, USA",
    "Ahjumawi Lava Springs",
    40.930421,
    -121.254536,
    "ahjumawilavaspringsstatepark",
  ],
  [
    "Anza-Borrego Desert State Park, California, USA",
    "Anza-Borrego Desert",
    32.991859,
    -116.435268,
    "anzaborregodesertstatepark",
  ],
  [
    "Benbow State Recreation Area, California, USA",
    "Benbow",
    40.361723,
    -124.148582,
    "benbowstaterecreationarea",
  ],
  [
    "Caspar Headlands State Natural Reserve, California, USA",
    "Caspar Headlands",
    39.386476,
    -123.814655,
    "casparheadlandsstatenaturalreserve",
  ],
  [
    "Castle Crags State Park, California, USA",
    "Castle Crags",
    41.17106,
    -122.351407,
    "castlecragsstatepark",
  ],
  [
    "Del Norte Coast Redwoods State Park, California, USA",
    "Del Norte Coast Redwoods",
    41.578145,
    -124.05835,
    "delnortecoastredwoodsstatepark",
  ],
  [
    "Estero Bluffs State Park, California, USA",
    "Estero Bluffs",
    35.174553,
    -121.189175,
    "esterobluffsstatepark",
  ],
  [
    "Fort Ross State Park, California, USA",
    "Fort Ross",
    38.50242,
    -123.29855,
    "fortrossstatepark",
  ],
  [
    "Grizzly Creek Redwoods State Park, California, USA",
    "Grizzly Creek Redwoods",
    40.09382,
    -123.91035,
    "grizzlycreekredwoodsstatepark",
  ],
  [
    "Grover Hot Springs State Park, California, USA",
    "Grover Hot Springs",
    38.700462,
    -119.837678,
    "groverhotspringsstatepark",
  ],
  [
    "Harry A. Merlo State Recreation Area, California, USA",
    "Harry A. Merlo",
    40.035989,
    -123.839832,
    "harryamerslostaterecreationarea",
  ],
  [
    "Hendy Woods State Park, California, USA",
    "Hendy Woods",
    40.481432,
    -124.052609,
    "hendywoodsstatepark",
  ],
  [
    "Humboldt Lagoons State Park, California, USA",
    "Humboldt Lagoons",
    41.189846,
    -124.121738,
    "humboldtlagoonsstatepark",
  ],
  [
    "John Little State Natural Reserve, California, USA",
    "John Little Reserve",
    38.2454,
    -122.65017,
    "johnlittlesta",
  ],
  [
    "Julia Pfeiffer Burns State Park, California, USA",
    "Julia Pfeiffer Burns",
    36.15582,
    -121.63765,
    "juliapfeifferburnsstatepark",
  ],
  [
    "Kruse Rhododendron State Natural Reserve, California, USA",
    "Kruse Rhododendron",
    39.338704,
    -123.84828,
    "kruserhododendronstatenaturalreserve",
  ],
  [
    "Limekiln State Park, California, USA",
    "Limekiln",
    36.10543,
    -121.55855,
    "limekilnstatepark",
  ],
  [
    "Manchester State Park, California, USA",
    "Manchester",
    39.452979,
    -124.26165,
    "manchesterstatepark",
  ],
  [
    "McArthur-Burney Falls State Park, California, USA",
    "McArthur-Burney Falls",
    40.814345,
    -121.424544,
    "mcarthurburneyfallsstatepark",
  ],
  [
    "Mendocino National Forest, California, USA",
    "Mendocino NF",
    39.5938,
    -123.339,
    "mendocinonationalforest",
  ],
  [
    "Mono Lake Tufa State Natural Reserve, California, USA",
    "Mono Lake Tufa",
    38.0369,
    -119.0092,
    "monolaketu StateNaturalReserve",
  ],
  [
    "Navarro River Redwoods State Park, California, USA",
    "Navarro River Redwoods",
    38.545717,
    -123.87545,
    "navarroriverredwoodsstatepark",
  ],
  [
    "Patrick's Point State Park, California, USA",
    "Patrick's Point",
    41.0857,
    -124.23156,
    "patrickspointstatepark",
  ],
  [
    "Pfeiffer Big Sur State Park, California, USA",
    "Pfeiffer Big Sur",
    36.2716,
    -121.8076,
    "pfeifferbigsurstatepark",
  ],
  [
    "Plumas-Eureka State Park, California, USA",
    "Plumas‑Eureka",
    39.8588,
    -120.6637,
    "plumaseurekastatepark",
  ],
  [
    "Point Sur State Park, California, USA",
    "Point Sur",
    35.313516,
    -121.136443,
    "pointsurstatepark",
  ],
  [
    "Prairie Creek Redwoods State Park, California, USA",
    "Prairie Creek Redwoods",
    41.3068,
    -124.0106,
    "prairiecreekredwoodsstatepark",
  ],
  [
    "Richardson Grove State Park, California, USA",
    "Richardson Grove",
    39.5417,
    -123.7605,
    "richardsongrovestatepark",
  ],
  [
    "Salt Point State Park, California, USA",
    "Salt Point",
    38.5656,
    -123.4006,
    "saltpointstatepark",
  ],
  [
    "Van Damme State Park, California, USA",
    "Van Damme",
    39.3017,
    -123.8147,
    "vandammestatepark",
  ],
  [
    "Crawford State Park, Colorado, USA",
    "Crawford",
    38.2269,
    -107.571,
    "crawfordstatepark",
  ],
  [
    "Gunnison National Forest, Colorado, USA",
    "Gunnison NF",
    38.640278,
    -107.035278,
    "gunnisonnationalforest",
  ],
  [
    "Jackson Lake State Park, Colorado, USA",
    "Jackson Lake",
    40.4672,
    -104.7787,
    "jacksonlakestatepark",
  ],
  [
    "John Martin Reservoir, Colorado, USA",
    "John Martin Reservoir",
    37.7053,
    -102.9086,
    "johnmartinreservoir",
  ],
  [
    "Navajo State Park, Colorado, USA",
    "Navajo State Park",
    38.0504,
    -108.1403,
    "navajostatepark",
  ],
  [
    "Paonia State Park, Colorado, USA",
    "Paonia",
    38.9531,
    -107.6022,
    "paoniastatepark",
  ],
  [
    "Pearl Lake State Park, Colorado, USA",
    "Pearl Lake",
    40.0044,
    -105.3626,
    "pearllakestatepark",
  ],
  [
    "Ridgway State Park, Colorado, USA",
    "Ridgway",
    38.1526,
    -107.7713,
    "ridgwaystatepark",
  ],
  [
    "Slumgullion Center County Park, Colorado, USA",
    "Slumgullion",
    38.0696,
    -107.438,
    "slumgullioncountypark",
  ],
  [
    "Stagecoach State Park, Colorado, USA",
    "Stagecoach",
    40.3442,
    -106.7814,
    "stagecoachstatepark",
  ],
  [
    "Bladon Springs State Park, Alabama, USA",
    "Bladon Springs , Alabama",
    31.7311,
    -88.1942,
    "bladonspringsstateparkalabama",
  ],
  [
    "Conecuh National Forest, Alabama, USA",
    "Conecuh National Forest, Alabama",
    31.0983,
    -86.6383,
    "conecuhnationalforestalabama",
  ],
  [
    "Chilkoot Lake State Recreation Area, Alaska, USA",
    "Chilkoot Lake  Area, Alaska",
    59.335833,
    -135.563611,
    "chilkootlakestaterecreationareaalaska",
  ],
  [
    "Kachemak Bay State Park, Alaska, USA",
    "Kachemak Bay , Alaska",
    59.5328,
    -151.21,
    "kachemakbaystateparkalaska",
  ],
  [
    "Sandspit Point State Marine Park, Alaska, USA",
    "Sandspit Point State Marine Park, Alaska",
    59.936944,
    -149.320556,
    "sandspitpointstatemarineparkalaska",
  ],
  [
    "Alamo Lake State Park, Arizona, USA",
    "Alamo Lake , Arizona",
    34.232222,
    -113.602778,
    "alamolakestateparkarizona",
  ],
  [
    "Kartchner Caverns State Park, Arizona, USA",
    "Kartchner Caverns , Arizona",
    31.8375,
    -110.347222,
    "kartchnercavernsstateparkarizona",
  ],
  [
    "Oracle State Park, Arizona, USA",
    "Oracle , Arizona",
    32.5911,
    -110.579,
    "oraclestateparkarizona",
  ],
  [
    "Petrified Forest National Park, Arizona, USA",
    "Petrified Forest National Park, Arizona",
    35.0881,
    -109.806,
    "petrifiedforestnationalparkarizona",
  ],
  [
    "Queen Wilhelmina State Park, Arkansas, USA",
    "Queen Wilhelmina , Arkansas",
    34.6846,
    -94.3692,
    "queenwilhelminastateparkarkansas",
  ],
  [
    "Admiral William Standley State Recreation Area, California, USA",
    "Admiral William Standley  Area, California",
    39.6464,
    -123.617,
    "admiralwilliamstandleystaterecreationareacalifornia",
  ],
  [
    "Ahjumawi Lava Springs State Park, California, USA",
    "Ahjumawi Lava Springs , California",
    41.1361,
    -121.418,
    "ahjumawilavaspringsstateparkcalifornia",
  ],
  [
    "Anza-Borrego Desert State Park, California, USA",
    "Anza-Borrego Desert , California",
    33.2592,
    -116.399,
    "anzaborregodesertstateparkcalifornia",
  ],
  [
    "Benbow State Recreation Area, California, USA",
    "Benbow  Area, California",
    40.066671,
    -123.789338,
    "benbowstaterecreationareacalifornia",
  ],
  [
    "Caspar Headlands State Natural Reserve, California, USA",
    "Caspar Headlands State Natural Reserve, California",
    39.359789,
    -123.821876,
    "casparheadlandsstatenaturalreservecalifornia",
  ],
  [
    "Castle Crags State Park, California, USA",
    "Castle Crags , California",
    41.171111,
    -122.351667,
    "castlecragsstateparkcalifornia",
  ],
  [
    "Del Norte Coast Redwoods State Park, California, USA",
    "Del Norte Coast Redwoods , California",
    41.6708,
    -124.117,
    "delnortecoastredwoodsstateparkcalifornia",
  ],
  [
    "Estero Bluffs State Park, California, USA",
    "Estero Bluffs , California",
    35.448056,
    -120.931944,
    "esterobluffsstateparkcalifornia",
  ],
  [
    "Grizzly Creek Redwoods State Park, California, USA",
    "Grizzly Creek Redwoods , California",
    40.4853,
    -123.906,
    "grizzlycreekredwoodsstateparkcalifornia",
  ],
  [
    "Grover Hot Springs State Park, California, USA",
    "Grover Hot Springs , California",
    38.7014,
    -119.839,
    "groverhotspringsstateparkcalifornia",
  ],
  [
    "Harry A. Merlo State Recreation Area, California, USA",
    "Harry A. Merlo  Area, California",
    41.1914,
    -124.10539,
    "harryamerlostaterecreationareacalifornia",
  ],
  [
    "Hendy Woods State Park, California, USA",
    "Hendy Woods , California",
    39.066667,
    -123.466667,
    "hendywoodsstateparkcalifornia",
  ],
  [
    "Humboldt Lagoons State Park, California, USA",
    "Humboldt Lagoons , California",
    41.2306,
    -124.103,
    "humboldtlagoonsstateparkcalifornia",
  ],
  [
    "John Little State Natural Reserve, California, USA",
    "John Little State Natural Reserve, California",
    36.1167,
    -121.633,
    "johnlittlestatenaturalreservecalifornia",
  ],
  [
    "Joshua Tree National Park, California, USA",
    "Joshua Tree National Park, California",
    33.748381,
    -115.819308,
    "joshuatreenationalparkcalifornia",
  ],
  [
    "Julia Pfeiffer Burns State Park, California, USA",
    "Julia Pfeiffer Burns , California",
    36.168056,
    -121.67,
    "juliapfeifferburnsstateparkcalifornia",
  ],
  [
    "Kruse Rhododendron State Natural Reserve, California, USA",
    "Kruse Rhododendron State Natural Reserve, California",
    38.593056,
    -123.339167,
    "kruserhododendronstatenaturalreservecalifornia",
  ],
  [
    "Limekiln State Park, California, USA",
    "Limekiln , California",
    36.01,
    -121.518333,
    "limekilnstateparkcalifornia",
  ],
  [
    "Manchester State Park, California, USA",
    "Manchester , California",
    38.9739,
    -123.713,
    "manchesterstateparkcalifornia",
  ],
  [
    "Mendocino National Forest, California, USA",
    "Mendocino National Forest, California",
    39.5625,
    -122.8125,
    "mendocinonationalforestcalifornia",
  ],
  [
    "Mono Lake Tufa State Natural Reserve, California, USA",
    "Mono Lake Tufa State Natural Reserve, California",
    37.9453,
    -119.036,
    "monolaketufastatenaturalreservecalifornia",
  ],
  [
    "Navarro River Redwoods State Park, California, USA",
    "Navarro River Redwoods , California",
    39.175,
    -123.676,
    "navarroriverredwoodsstateparkcalifornia",
  ],
  [
    "Patrick's Point State Park, California, USA",
    "Patrick's Point , California",
    40.1358,
    -124.161,
    "patrickspointstateparkcalifornia",
  ],
  [
    "Pfeiffer Big Sur State Park, California, USA",
    "Pfeiffer Big Sur , California",
    36.2476,
    -121.782,
    "pfeifferbigsurstateparkcalifornia",
  ],
  [
    "Plumas-Eureka State Park, California, USA",
    "Plumas-Eureka , California",
    39.761111,
    -120.706667,
    "plumaseurekastateparkcalifornia",
  ],
  [
    "Prairie Creek Redwoods State Park, California, USA",
    "Prairie Creek Redwoods , California",
    41.4038,
    -124.038,
    "prairiecreekredwoodsstateparkcalifornia",
  ],
  [
    "Richardson Grove State Park, California, USA",
    "Richardson Grove , California",
    40.0167,
    -123.8,
    "richardsongrovestateparkcalifornia",
  ],
  [
    "Salt Point State Park, California, USA",
    "Salt Point , California",
    38.5736,
    -123.326,
    "saltpointstateparkcalifornia",
  ],
  [
    "Van Damme State Park, California, USA",
    "Van Damme , California",
    39.275,
    -123.767,
    "vandammestateparkcalifornia",
  ],
  [
    "Crawford State Park, Colorado, USA",
    "Crawford , Colorado",
    38.6872,
    -107.596,
    "crawfordstateparkcolorado",
  ],
  [
    "Great Sand Dunes National Park, Colorado, USA",
    "Great Sand Dunes National Park, Colorado",
    37.77654,
    -105.62886,
    "greatsanddunesnationalparkcolorado",
  ],
  [
    "Gunnison National Forest, Colorado, USA",
    "Gunnison National Forest, Colorado",
    38.703236,
    -107.2167,
    "gunnisonnationalforestcolorado",
  ],
  [
    "Jackson Lake State Park, Colorado, USA",
    "Jackson Lake , Colorado",
    40.3828,
    -104.092,
    "jacksonlakestateparkcolorado",
  ],
  [
    "John Martin Reservoir, Colorado, USA",
    "John Martin Reservoir, Colorado",
    38.066,
    -102.954,
    "johnmartinreservoircolorado",
  ],
  [
    "Navajo State Park, Colorado, USA",
    "Navajo , Colorado",
    37.0089,
    -107.409,
    "navajostateparkcolorado",
  ],
  [
    "Paonia State Park, Colorado, USA",
    "Paonia , Colorado",
    38.9828,
    -107.346,
    "paoniastateparkcolorado",
  ],
  [
    "Pearl Lake State Park, Colorado, USA",
    "Pearl Lake , Colorado",
    40.7867,
    -106.891,
    "pearllakestateparkcolorado",
  ],
  [
    "Ridgway State Park, Colorado, USA",
    "Ridgway , Colorado",
    38.2125,
    -107.734,
    "ridgwaystateparkcolorado",
  ],
  [
    "Stagecoach State Park, Colorado, USA",
    "Stagecoach , Colorado",
    40.2883,
    -106.862,
    "stagecoachstateparkcolorado",
  ],
  [
    "State Forest State Park, Colorado, USA",
    "State Forest , Colorado",
    40.5114,
    -106.01,
    "stateforeststateparkcolorado",
  ],
  [
    "Steamboat Lake State Park, Colorado, USA",
    "Steamboat Lake , Colorado",
    40.8086,
    -106.952,
    "steamboatlakestateparkcolorado",
  ],
  [
    "Sylvan Lake State Park, Colorado, USA",
    "Sylvan Lake , Colorado",
    39.5439,
    -106.755,
    "sylvanlakestateparkcolorado",
  ],
  [
    "Vega State Park, Colorado, USA",
    "Vega , Colorado",
    39.2244,
    -107.793,
    "vegastateparkcolorado",
  ],
  [
    "White River National Forest, Colorado, USA",
    "White River National Forest, Colorado",
    39.56072,
    -106.8925,
    "whiterivernationalforestcolorado",
  ],
  [
    "Stephen C. Foster State Park, Georgia, USA",
    "Stephen C. Foster , Georgia",
    30.823106,
    -82.36444,
    "stephencfosterstateparkgeorgia",
  ],
  [
    "Koke'e State Park, Hawaii, USA",
    "Koke'e , Hawaii",
    22.1303,
    -159.659,
    "kokeestateparkhawaii",
  ],
  [
    "Pala'au State Park, Hawaii, USA",
    "Pala'au , Hawaii",
    21.1744,
    -157.008,
    "palaaustateparkhawaii",
  ],
  [
    "Polipoli Spring State Recreation Area, Hawaii, USA",
    "Polipoli Spring  Area, Hawaii",
    20.680556,
    -156.3325,
    "polipolispringstaterecreationareahawaii",
  ],
  [
    "Wai'anapanapa State Park, Hawaii, USA",
    "Wai'anapanapa , Hawaii",
    20.7858,
    -155.997,
    "waianapanapastateparkhawaii",
  ],
  [
    "Waimea Canyon State Park, Hawaii, USA",
    "Waimea Canyon , Hawaii",
    22.056111,
    -159.665278,
    "waimeacanyonstateparkhawaii",
  ],
  [
    "Bear Lake State Park, Idaho, USA",
    "Bear Lake , Idaho",
    42.1111,
    -111.273,
    "bearlakestateparkidaho",
  ],
  [
    "Castle Rocks State Park, Idaho, USA",
    "Castle Rocks , Idaho",
    42.137,
    -113.677,
    "castlerocksstateparkidaho",
  ],
  [
    "City of Rocks National Reserve, Idaho, USA",
    "City of Rocks National Reserve, Idaho",
    42.076,
    -113.702,
    "cityofrocksnationalreserveidaho",
  ],
  [
    "Harriman State Park, Idaho, USA",
    "Harriman , Idaho",
    41.2431,
    -74.1006,
    "harrimanstateparkidaho",
  ],
  [
    "Henrys Lake State Park, Idaho, USA",
    "Henrys Lake , Idaho",
    44.62,
    -111.373889,
    "henryslakestateparkidaho",
  ],
  [
    "Priest Lake State Park, Idaho, USA",
    "Priest Lake , Idaho",
    48.6134,
    -116.832,
    "priestlakestateparkidaho",
  ],
  [
    "Cedar Bluff State Park, Kansas, USA",
    "Cedar Bluff , Kansas",
    38.7747,
    -99.7717,
    "cedarbluffstateparkkansas",
  ],
  [
    "Cross Timbers State Park, Kansas, USA",
    "Cross Timbers , Kansas",
    37.7694,
    -95.9392,
    "crosstimbersstateparkkansas",
  ],
  [
    "Fall River State Park, Kansas, USA",
    "Fall River , Kansas",
    37.655,
    -96.0933,
    "fallriverstateparkkansas",
  ],
  [
    "Kanopolis State Park, Kansas, USA",
    "Kanopolis , Kansas",
    38.6572,
    -97.9997,
    "kanopolisstateparkkansas",
  ],
  [
    "Lake Scott State Park, Kansas, USA",
    "Lake Scott , Kansas",
    38.6756,
    -100.917,
    "lakescottstateparkkansas",
  ],
  [
    "Little Jerusalem Badlands State Park, Kansas, USA",
    "Little Jerusalem Badlands , Kansas",
    38.8025,
    -100.9425,
    "littlejerusalembadlandsstateparkkansas",
  ],
  [
    "Lovewell State Park, Kansas, USA",
    "Lovewell , Kansas",
    38.9044,
    -98.0508,
    "lovewellstateparkkansas",
  ],
  [
    "Meade State Park, Kansas, USA",
    "Meade , Kansas",
    37.1722,
    -100.451,
    "meadestateparkkansas",
  ],
  [
    "Mushroom Rock State Park, Kansas, USA",
    "Mushroom Rock , Kansas",
    38.7258,
    -98.0306,
    "mushroomrockstateparkkansas",
  ],
  [
    "Webster State Park, Kansas, USA",
    "Webster , Kansas",
    39.4097,
    -99.4494,
    "websterstateparkkansas",
  ],
  [
    "Wilson State Park, Kansas, USA",
    "Wilson , Kansas",
    44.0289,
    -84.8044,
    "wilsonstateparkkansas",
  ],
  [
    "Baxter State Park, Maine, USA",
    "Baxter , Maine",
    46.0333,
    -68.9333,
    "baxterstateparkmaine",
  ],
  [
    "Cobscook Bay State Park, Maine, USA",
    "Cobscook Bay , Maine",
    44.841468,
    -67.150262,
    "cobscookbaystateparkmaine",
  ],
  [
    "Grafton Notch State Park, Maine, USA",
    "Grafton Notch , Maine",
    44.593391,
    -70.947853,
    "graftonnotchstateparkmaine",
  ],
  [
    "Lily Bay State Park, Maine, USA",
    "Lily Bay , Maine",
    45.57,
    -69.55,
    "lilybaystateparkmaine",
  ],
  [
    "Mount Blue State Park, Maine, USA",
    "Mount Blue , Maine",
    44.7353,
    -70.379,
    "mountbluestateparkmaine",
  ],
  [
    "Peaks-Kenny State Park, Maine, USA",
    "Peaks-Kenny , Maine",
    45.2581,
    -69.27,
    "peakskennystateparkmaine",
  ],
  [
    "Quoddy Head State Park, Maine, USA",
    "Quoddy Head , Maine",
    44.807025,
    -66.967478,
    "quoddyheadstateparkmaine",
  ],
  [
    "Rangeley Lake State Park, Maine, USA",
    "Rangeley Lake , Maine",
    44.945278,
    -70.693889,
    "rangeleylakestateparkmaine",
  ],
  [
    "Roque Bluffs State Park, Maine, USA",
    "Roque Bluffs , Maine",
    44.615,
    -67.4878,
    "roquebluffsstateparkmaine",
  ],
  [
    "Clear Lake State Park, Michigan, USA",
    "Clear Lake , Michigan",
    39.01,
    -122.809,
    "clearlakestateparkmichigan",
  ],
  [
    "Craig Lake State Park, Michigan, USA",
    "Craig Lake , Michigan",
    46.6119,
    -88.1781,
    "craiglakestateparkmichigan",
  ],
  [
    "Fayette Historic State Park, Michigan, USA",
    "Fayette Historic , Michigan",
    45.71667,
    -86.66111,
    "fayettehistoricstateparkmichigan",
  ],
  [
    "Fort Wilkins Historic State Park, Michigan, USA",
    "Fort Wilkins Historic , Michigan",
    47.467222,
    -87.869722,
    "fortwilkinshistoricstateparkmichigan",
  ],
  [
    "Hiawatha National Forest, Michigan, USA",
    "Hiawatha National Forest, Michigan",
    46.1333,
    -86.6667,
    "hiawathanationalforestmichigan",
  ],
  [
    "Hoeft State Park, Michigan, USA",
    "Hoeft , Michigan",
    45.4625,
    -83.88,
    "hoeftstateparkmichigan",
  ],
  [
    "Isle Royale National Park, Michigan, USA",
    "Isle Royale National Park, Michigan",
    47.995865,
    -88.90929,
    "isleroyalenationalparkmichigan",
  ],
  [
    "Lake Gogebic State Park, Michigan, USA",
    "Lake Gogebic , Michigan",
    46.4575,
    -89.5761,
    "lakegogebicstateparkmichigan",
  ],
  [
    "Leelanau State Park, Michigan, USA",
    "Leelanau , Michigan",
    45.1864,
    -85.5622,
    "leelanaustateparkmichigan",
  ],
  [
    "Negwegon State Park, Michigan, USA",
    "Negwegon , Michigan",
    44.8561,
    -83.3269,
    "negwegonstateparkmichigan",
  ],
  [
    "Onaway State Park, Michigan, USA",
    "Onaway , Michigan",
    45.4314,
    -84.2292,
    "onawaystateparkmichigan",
  ],
  [
    "Porcupine Mountains Wilderness State Park, Michigan, USA",
    "Porcupine Mountains Wilderness , Michigan",
    46.782222,
    -89.754167,
    "porcupinemountainswildernessstateparkmichigan",
  ],
  [
    "Wells State Park, Michigan, USA",
    "Wells , Michigan",
    42.1464,
    -72.0669,
    "wellsstateparkmichigan",
  ],
  [
    "Wilderness State Park, Michigan, USA",
    "Wilderness , Michigan",
    45.7342,
    -84.9028,
    "wildernessstateparkmichigan",
  ],
  [
    "Big Bog State Recreation Area, Minnesota, USA",
    "Big Bog  Area, Minnesota",
    48.1928,
    -94.5119,
    "bigbogstaterecreationareaminnesota",
  ],
  [
    "Cascade River State Park, Minnesota, USA",
    "Cascade River , Minnesota",
    47.7097,
    -90.5222,
    "cascaderiverstateparkminnesota",
  ],
  [
    "Garden Island State Recreation Area, Minnesota, USA",
    "Garden Island  Area, Minnesota",
    49.1778,
    -94.8586,
    "gardenislandstaterecreationareaminnesota",
  ],
  [
    "Hayes Lake State Park, Minnesota, USA",
    "Hayes Lake , Minnesota",
    48.6231,
    -95.5075,
    "hayeslakestateparkminnesota",
  ],
  [
    "Itasca State Park, Minnesota, USA",
    "Itasca , Minnesota",
    47.2397,
    -95.2075,
    "itascastateparkminnesota",
  ],
  [
    "La Salle Lake State Recreation Area, Minnesota, USA",
    "La Salle Lake  Area, Minnesota",
    47.348,
    -95.166043,
    "lasallelakestaterecreationareaminnesota",
  ],
  [
    "Old Mill State Park, Minnesota, USA",
    "Old Mill , Minnesota",
    48.3614,
    -96.5703,
    "oldmillstateparkminnesota",
  ],
  [
    "Savanna Portage State Park, Minnesota, USA",
    "Savanna Portage , Minnesota",
    46.8375,
    -93.1567,
    "savannaportagestateparkminnesota",
  ],
  [
    "Scenic State Park, Minnesota, USA",
    "Scenic , Minnesota",
    47.7214,
    -93.57,
    "scenicstateparkminnesota",
  ],
  [
    "Split Rock Lighthouse State Park, Minnesota, USA",
    "Split Rock Lighthouse , Minnesota",
    47.1919,
    -91.3928,
    "splitrocklighthousestateparkminnesota",
  ],
  [
    "Temperance River State Park, Minnesota, USA",
    "Temperance River , Minnesota",
    47.5542,
    -90.8722,
    "temperanceriverstateparkminnesota",
  ],
  [
    "Voyageurs National Park, Minnesota, USA",
    "Voyageurs National Park, Minnesota",
    48.5,
    -92.883333,
    "voyageursnationalparkminnesota",
  ],
  [
    "Zippel Bay State Park, Minnesota, USA",
    "Zippel Bay , Minnesota",
    48.8639,
    -94.8594,
    "zippelbaystateparkminnesota",
  ],
  [
    "Current River State Park, Missouri, USA",
    "Current River , Missouri",
    37.3217,
    -91.4367,
    "currentriverstateparkmissouri",
  ],
  [
    "Ackley Lake State Park, Montana, USA",
    "Ackley Lake , Montana",
    46.9578,
    -109.941,
    "ackleylakestateparkmontana",
  ],
  [
    "Beaverhead Rock State Park, Montana, USA",
    "Beaverhead Rock , Montana",
    45.386389,
    -112.459722,
    "beaverheadrockstateparkmontana",
  ],
  [
    "Fish Creek State Park, Montana, USA",
    "Fish Creek , Montana",
    46.99,
    -114.715833,
    "fishcreekstateparkmontana",
  ],
  [
    "Glacier National Park, Montana, USA",
    "Glacier National Park, Montana",
    48.755,
    -113.8,
    "glaciernationalparkmontana",
  ],
  [
    "Logan State Park, Montana, USA",
    "Logan , Montana",
    48.033056,
    -115.066389,
    "loganstateparkmontana",
  ],
  [
    "Medicine Rocks State Park, Montana, USA",
    "Medicine Rocks , Montana",
    46.0444,
    -104.471,
    "medicinerocksstateparkmontana",
  ],
  [
    "Beaver Dam State Park, Nevada, USA",
    "Beaver Dam , Nevada",
    39.2111,
    -89.9761,
    "beaverdamstateparknevada",
  ],
  [
    "Echo Canyon State Park, Nevada, USA",
    "Echo Canyon , Nevada",
    37.91,
    -114.261,
    "echocanyonstateparknevada",
  ],
  [
    "Rye Patch Reservoir, Nevada, USA",
    "Rye Patch Reservoir, Nevada",
    40.4706,
    -118.309,
    "ryepatchreservoirnevada",
  ],
  [
    "Clayton Lake, Oklahoma, USA",
    "Clayton Lake, Oklahoma",
    34.5431,
    -95.3094,
    "claytonlakeoklahoma",
  ],
  [
    "Gloss Mountain State Park, Oklahoma, USA",
    "Gloss Mountain , Oklahoma",
    36.3667,
    -98.5789,
    "glossmountainstateparkoklahoma",
  ],
  [
    "McGee Creek State Park, Oklahoma, USA",
    "McGee Creek , Oklahoma",
    34.33,
    -95.8617,
    "mcgeecreekstateparkoklahoma",
  ],
  [
    "Talimena State Park, Oklahoma, USA",
    "Talimena , Oklahoma",
    34.7843,
    -94.9536,
    "talimenastateparkoklahoma",
  ],
  [
    "Cape Blanco State Park, Oregon, USA",
    "Cape Blanco , Oregon",
    42.835833,
    -124.542778,
    "capeblancostateparkoregon",
  ],
  [
    "Cape Lookout State Park, Oregon, USA",
    "Cape Lookout , Oregon",
    45.3526,
    -123.97235,
    "capelookoutstateparkoregon",
  ],
  [
    "Cape Sebastian, Oregon, USA",
    "Cape Sebastian, Oregon",
    42.31932,
    -124.42768,
    "capesebastianoregon",
  ],
  [
    "Cascadia State Park, Oregon, USA",
    "Cascadia , Oregon",
    44.3982,
    -122.473,
    "cascadiastateparkoregon",
  ],
  [
    "Catherine Creek State Park, Oregon, USA",
    "Catherine Creek , Oregon",
    45.15292,
    -117.73743,
    "catherinecreekstateparkoregon",
  ],
  [
    "Collier Memorial State Park, Oregon, USA",
    "Collier Memorial , Oregon",
    42.6432,
    -121.883,
    "colliermemorialstateparkoregon",
  ],
  [
    "Cottonwood Canyon State Park, Oregon, USA",
    "Cottonwood Canyon , Oregon",
    45.478371,
    -120.47233,
    "cottonwoodcanyonstateparkoregon",
  ],
  [
    "Humbug Mountain State Park, Oregon, USA",
    "Humbug Mountain , Oregon",
    42.6865,
    -124.436,
    "humbugmountainstateparkoregon",
  ],
  [
    "Joseph H. Stewart State Recreation Area, Oregon, USA",
    "Joseph H. Stewart  Area, Oregon",
    42.6843,
    -122.619,
    "josephhstewartstaterecreationareaoregon",
  ],
  [
    "Minam State Recreation Area, Oregon, USA",
    "Minam  Area, Oregon",
    45.7832,
    -117.718,
    "minamstaterecreationareaoregon",
  ],
  [
    "Prineville Reservoir State Park, Oregon, USA",
    "Prineville Reservoir , Oregon",
    44.133056,
    -120.562222,
    "prinevillereservoirstateparkoregon",
  ],
  [
    "Saddle Mountain State Natural Area, Oregon, USA",
    "Saddle Mountain State Natural Area, Oregon",
    45.9662,
    -123.686,
    "saddlemountainstatenaturalareaoregon",
  ],
  [
    "Sitka Sedge State Natural Area, Oregon, USA",
    "Sitka Sedge State Natural Area, Oregon",
    45.263,
    -123.953917,
    "sitkasedgestatenaturalareaoregon",
  ],
  [
    "Umpqua National Forest, Oregon, USA",
    "Umpqua National Forest, Oregon",
    43.2225,
    -122.254,
    "umpquanationalforestoregon",
  ],
  [
    "White River Falls State Park, Oregon, USA",
    "White River Falls , Oregon",
    45.2415,
    -121.096,
    "whiteriverfallsstateparkoregon",
  ],
  [
    "Willamette National Forest, Oregon, USA",
    "Willamette National Forest, Oregon",
    44.10947,
    -122.18353,
    "willamettenationalforestoregon",
  ],
  [
    "Cherry Springs State Park, Pennsylvania, USA",
    "Cherry Springs , Pennsylvania",
    41.6628,
    -77.8231,
    "cherryspringsstateparkpennsylvania",
  ],
  [
    "Susquehannock State Forest, Pennsylvania, USA",
    "Susquehannock State Forest, Pennsylvania",
    41.731944,
    -78.305556,
    "susquehannockstateforestpennsylvania",
  ],
  [
    "Big Bend Ranch State Park, Texas, USA",
    "Big Bend Ranch , Texas",
    29.5306,
    -104.154,
    "bigbendranchstateparktexas",
  ],
  [
    "Colorado Bend State Park, Texas, USA",
    "Colorado Bend , Texas",
    31.0539,
    -98.4922,
    "coloradobendstateparktexas",
  ],
  [
    "Copper Breaks State Park, Texas, USA",
    "Copper Breaks , Texas",
    34.1114,
    -99.7525,
    "copperbreaksstateparktexas",
  ],
  [
    "Davis Mountains State Park, Texas, USA",
    "Davis Mountains , Texas",
    30.5958,
    -103.933,
    "davismountainsstateparktexas",
  ],
  [
    "Kickapoo Cavern State Park, Texas, USA",
    "Kickapoo Cavern , Texas",
    29.61189,
    -100.44842,
    "kickapoocavernstateparktexas",
  ],
  [
    "Lost Maples State Natural Area, Texas, USA",
    "Lost Maples State Natural Area, Texas",
    29.8197,
    -99.5831,
    "lostmaplesstatenaturalareatexas",
  ],
  [
    "Antelope Island State Park, Utah, USA",
    "Antelope Island , Utah",
    40.9581,
    -112.207,
    "antelopeislandstateparkutah",
  ],
  [
    "Arches National Park, Utah, USA",
    "Arches National Park, Utah",
    38.728056,
    -109.54,
    "archesnationalparkutah",
  ],
  [
    "Bear Lake State Park, Utah, USA",
    "Bear Lake , Utah",
    42.1111,
    -111.273,
    "bearlakestateparkutah",
  ],
  [
    "Bryce Canyon National Park, Utah, USA",
    "Bryce Canyon National Park, Utah",
    37.64,
    -112.17,
    "brycecanyonnationalparkutah",
  ],
  [
    "Cedar Breaks National Monument, Utah, USA",
    "Cedar Breaks National Monument, Utah",
    37.6425,
    -112.849,
    "cedarbreaksnationalmonumentutah",
  ],
  [
    "Coral Pink Sand Dunes State Park, Utah, USA",
    "Coral Pink Sand Dunes , Utah",
    37.0378,
    -112.72,
    "coralpinksanddunesstateparkutah",
  ],
  [
    "East Canyon State Park, Utah, USA",
    "East Canyon , Utah",
    40.9011,
    -111.587,
    "eastcanyonstateparkutah",
  ],
  [
    "Green River State Park, Utah, USA",
    "Green River , Utah",
    38.9914,
    -110.154,
    "greenriverstateparkutah",
  ],
  [
    "Hovenweep National Monument, Utah, USA",
    "Hovenweep National Monument, Utah",
    37.383611,
    -109.068333,
    "hovenweepnationalmonumentutah",
  ],
  [
    "Jordanelle State Park, Utah, USA",
    "Jordanelle , Utah",
    40.620278,
    -111.411667,
    "jordanellestateparkutah",
  ],
  [
    "Kodachrome Basin State Park, Utah, USA",
    "Kodachrome Basin , Utah",
    37.5006,
    -112.001,
    "kodachromebasinstateparkutah",
  ],
  [
    "Natural Bridges National Monument, Utah, USA",
    "Natural Bridges National Monument, Utah",
    37.601383,
    -110.013744,
    "naturalbridgesnationalmonumentutah",
  ],
  [
    "Piute State Park, Utah, USA",
    "Piute , Utah",
    38.3181,
    -112.198,
    "piutestateparkutah",
  ],
  [
    "Rainbow Bridge National Monument, Utah, USA",
    "Rainbow Bridge National Monument, Utah",
    37.077222,
    -110.964167,
    "rainbowbridgenationalmonumentutah",
  ],
  [
    "Rockport State Park, Utah, USA",
    "Rockport , Utah",
    48.4882,
    -121.615,
    "rockportstateparkutah",
  ],
  [
    "Steinaker State Park, Utah, USA",
    "Steinaker , Utah",
    40.5175,
    -109.53,
    "steinakerstateparkutah",
  ],
  [
    "Yuba State Park, Utah, USA",
    "Yuba , Utah",
    39.3789,
    -112.027,
    "yubastateparkutah",
  ],
  [
    "Big Deer State Park, Vermont, USA",
    "Big Deer , Vermont",
    44.2872,
    -72.2678,
    "bigdeerstateparkvermont",
  ],
  [
    "Boulder Beach State Park, Vermont, USA",
    "Boulder Beach , Vermont",
    44.2776,
    -72.2623,
    "boulderbeachstateparkvermont",
  ],
  [
    "Kettle Pond State Park, Vermont, USA",
    "Kettle Pond , Vermont",
    44.2944,
    -72.3078,
    "kettlepondstateparkvermont",
  ],
  [
    "Maidstone State Park, Vermont, USA",
    "Maidstone , Vermont",
    44.6387,
    -71.6434,
    "maidstonestateparkvermont",
  ],
  [
    "New Discovery State Park, Vermont, USA",
    "New Discovery , Vermont",
    44.320601,
    -72.290264,
    "newdiscoverystateparkvermont",
  ],
  [
    "Ricker Pond State Park, Vermont, USA",
    "Ricker Pond , Vermont",
    44.246,
    -72.254,
    "rickerpondstateparkvermont",
  ],
  [
    "Seyon Lodge State Park, Vermont, USA",
    "Seyon Lodge , Vermont",
    44.227,
    -72.304,
    "seyonlodgestateparkvermont",
  ],
  [
    "Stillwater State Park, Vermont, USA",
    "Stillwater , Vermont",
    44.2799,
    -72.2729,
    "stillwaterstateparkvermont",
  ],
  [
    "Highland County, Virginia, USA",
    "Highland County, Virginia",
    39.18,
    -83.6,
    "highlandcountyvirginia",
  ],
  [
    "James River State Park, Virginia, USA",
    "James River , Virginia",
    37.6222,
    -78.8172,
    "jamesriverstateparkvirginia",
  ],
  [
    "Staunton River State Park, Virginia, USA",
    "Staunton River , Virginia",
    36.6961,
    -78.6853,
    "stauntonriverstateparkvirginia",
  ],
  [
    "Brooks Memorial State Park, Washington, USA",
    "Brooks Memorial , Washington",
    45.94,
    -120.663889,
    "brooksmemorialstateparkwashington",
  ],
  [
    "Camp Wooten State Park, Washington, USA",
    "Camp Wooten , Washington",
    46.238333,
    -117.697778,
    "campwootenstateparkwashington",
  ],
  [
    "Colville National Forest, Washington, USA",
    "Colville National Forest, Washington",
    48.688,
    -117.625,
    "colvillenationalforestwashington",
  ],
  [
    "Crawford State Park, Washington, USA",
    "Crawford , Washington",
    38.6872,
    -107.596,
    "crawfordstateparkwashington",
  ],
  [
    "Fields Spring State Park, Washington, USA",
    "Fields Spring , Washington",
    46.077222,
    -117.171944,
    "fieldsspringstateparkwashington",
  ],
  [
    "Leadbetter Point State Park, Washington, USA",
    "Leadbetter Point , Washington",
    46.615,
    -124.06,
    "leadbetterpointstateparkwashington",
  ],
  [
    "Lyons Ferry State Park, Washington, USA",
    "Lyons Ferry , Washington",
    46.625,
    -118.21,
    "lyonsferrystateparkwashington",
  ],
  [
    "Mount Rainier National Park, Washington, USA",
    "Mount Rainier National Park, Washington",
    46.85,
    -121.75,
    "mountrainiernationalparkwashington",
  ],
  [
    "North Cascades National Park, Washington, USA",
    "North Cascades National Park, Washington",
    48.483056,
    -120.911389,
    "northcascadesnationalparkwashington",
  ],
  [
    "Olympic National Park, Washington, USA",
    "Olympic National Park, Washington",
    47.7,
    -123.75,
    "olympicnationalparkwashington",
  ],
  [
    "Palouse Falls State Park, Washington, USA",
    "Palouse Falls , Washington",
    46.6669,
    -118.224,
    "palousefallsstateparkwashington",
  ],
  [
    "Pearrygin Lake State Park, Washington, USA",
    "Pearrygin Lake , Washington",
    48.489722,
    -120.143056,
    "pearryginlakestateparkwashington",
  ],
  [
    "Big Bay State Park, Wisconsin, USA",
    "Big Bay , Wisconsin",
    46.8,
    -90.6728,
    "bigbaystateparkwisconsin",
  ],
  [
    "Chequamegon-Nicolet National Forest, Wisconsin, USA",
    "Chequamegon-Nicolet National Forest, Wisconsin",
    46.154722,
    -90.872778,
    "chequamegonnicoletnationalforestwisconsin",
  ],
  [
    "Newport State Park, Wisconsin, USA",
    "Newport , Wisconsin",
    45.235,
    -86.9942,
    "newport",
  ],
  [
    "Rock Island State Park, Wisconsin, USA",
    "Rock Island , Wisconsin",
    45.4158,
    -86.8194,
    "rockisland",
  ],
  [
    "Bighorn National Forest, Wyoming, USA",
    "Bighorn National Forest, Wyoming",
    44.5333,
    -107.35,
    "bighorn",
  ],
  [
    "Boysen State Park, Wyoming, USA",
    "Boysen , Wyoming",
    43.416624,
    -108.177319,
    "boysen",
  ],
  [
    "Bridger-Teton National Forest, Wyoming, USA",
    "Bridger-Teton National Forest, Wyoming",
    43.43,
    -110.725,
    "bridgerteton",
  ],
  [
    "Seminoe State Park, Wyoming, USA",
    "Seminoe , Wyoming",
    42.0586,
    -106.872,
    "seminoe",
  ],
] as const;

export const SPECIAL_LOCATIONS: SpecialLocation[] = [
  ...DARK_SITES,
  ...LARGE_CITIES,
] as const;

export const HIGH_LATITUDE_MESSAGE = `<h2>Galactic Core Below the Horizon</h2><p>The center of our galaxy, the Milky Way, lies in the constellation Sagittarius. In the sky, it has a fixed position just like a bright star, with a “declination” of about <strong>29 degrees south</strong>. Declination is a coordinate similar to latitude on Earth, but it’s used for the celestial sphere. Because the Galactic Core is so far south in the sky, your location on Earth determines whether you can see it at all.</p>

<p>If you live <strong>north of about 61° N</strong> — for example in northern Alaska, parts of Canada, or far northern Scandinavia — the Galactic Core never rises above the horizon, so it’s permanently hidden from view. The farther south you go, the higher it climbs in the sky at its peak each night. Around <strong>30° N</strong> (southern United States, North Africa, southern China) it reaches about 60° above the horizon. Near the <strong>29° S</strong> line (central Chile, South Africa, southern Australia), it passes directly overhead. In the far south, below <strong>61° S</strong> (deep Antarctica), the Galactic Core never sets and is visible all year round.</p>

<p>This is why astrophotographers often travel to southern latitudes — from there, the Milky Way’s core appears higher in the sky, stays visible longer, and can be seen in darker parts of the night.</p>

`;

export const LARGE_CITY_MESSAGE = `<h2>City Lights vs Star Light</h2><p>Even if the Galactic Core is high in the sky where you live, you might not be able to see the Milky Way at all if you are in or near a large city. This is because of <strong>light pollution</strong> — the glow from streetlights, buildings, billboards, and cars that scatters in the atmosphere and drowns out faint objects in the night sky. The Milky Way is made up of billions of stars, but most of them are faint. Under heavy light pollution, only the brightest stars remain visible, and the Milky Way’s soft, cloudlike glow disappears completely.</p>

<p>To see it clearly, you need to be under <strong>dark skies</strong> — far from cities, towns, and major roads. Astronomers often use the <strong>Bortle scale</strong> to measure sky darkness. In the brightest city skies (Bortle 9), you might see only a dozen stars. In very dark rural areas (Bortle 1–2), thousands of stars are visible, and the Milky Way shines brightly across the sky. If you live in an urban area, plan to travel at least an hour or two away from the city lights, ideally to a place protected from development such as a national park or an official “Dark Sky” preserve.</p>`;

export const SPECIAL_AREAS = {
  "los-angeles-area": "Los Angeles",
  "san-diego-area": "San Diego",
  "sf-bay-area": "San Francisco Bay Area",
  "shanghai-suzhou": "Shanghai/Suzhou",
  "pearl-river-delta": "Pearl River Delta",
  // Only keep area keys used by multiple locations
};
